apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-maskinporten-test
  namespace: pensjon-saksbehandling
  labels:
    team: pensjon-saksbehandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://pensjon-maskinporten-test.intern.dev.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      replyURLs:
        - https://pensjon-maskinporten-test.intern.dev.nav.no/login/oauth2/code/azure
        - http://localhost/login/oauth2/code/azure
      claims:
#        groups:
#          - id: "b15ec4e3-126e-494a-b510-e0a576eba92a" #Team Pensjon-saksbehandling
#          - id: "" #SAKSBEHANDLER
        extra:
          - NAVident
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: nav:pensjon/v1/vedtaksinformasjon
        - name: nav:pensjon/v3/alderspensjon
        - name: nav:pensjon/afpprivat
        - name: nav:pensjon/v1/ytelse
        - name: nav:pensjon/v1/ytelsehistorikk
        - name: nav:etterlatteytelser:vedtaksinformasjon.read
        - name: nav:pensjon/afpprivat/mottarafpprivat
        - name: nav:pensjon/afpprivat/fellesordningen
        - name: nav:uforetrygd:erungufor
        - name: nav:uforetrygd:tpordningene.harmottattuforeetter62.read
        - name: nav:uforetrygd:tpordningene.uforeperioder.read
        - name: nav:uforetrygd:tpordningene.harlopendevedtakomufore.read
        - name: nav:uforetrygd:tpordningene.haruforesoknadunderbehandling.read
        - name: nav:pensjon:folketrygdbeholdning
        - name: nav:pensjon/v1/samordning
        - name: nav:pensjon/v1/tpregisteret
        - name: nav:helse/v1/uforeopplysninger
        - name: nav:pensjon/alderspensjon/status
        - name: klp:oftp/simulering
        - name: nav:pensjonssimulator:simulering
        - name: spk:nav

  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 5m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
